### ISSUE TITLE
Localized versions of /roles/task/client/files/bin scripts?

### ISSUE THREAD

**Issue by decause** [ralphbean/lightsaber#23]
So, there are buggwarrior and taskwarrior rc files specific to users in <code>/lightsaber/roles/task/client/files</code>, but within <code>/bin</code>, scripts like <code>timesheet.sh</code> and <code>make-report.sh</code> have user-specific references hardcoded into them.

I'd like to discuss how best to "fork" these scripts, and how best to distribute them within lightsaber without clobbering other users' setups.

**Comment by ralphbean** [comment]
Hm... we should probably make them into ansible templates and use the `{{username}}` var.

**Comment by ralphbean** [comment]
Two years later, I'm pretty sure I'm not going to get to this.. ;)
